"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { ArrowUpRight, ArrowDownLeft, Loader2, Download, FileText, Printer, Globe, PlusCircle, Heart } from "lucide-react";
import { useSession } from "next-auth/react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import T from "@/components/T";

export default function TransactionsPage() {
  const { data: session } = useSession();
  const [userData, setUserData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  const userEmail = session?.user?.email;

  const fetchTransactions = async () => {
    if (!userEmail) return;
    try {
      setLoading(true);
      const res = await fetch(`/api/kyc?email=${userEmail}`);  
      const data = await res.json();
      setUserData(data);
    } catch (error) {
      console.error("Failed to fetch data", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTransactions();
    window.addEventListener("balanceUpdated", fetchTransactions);
    return () => window.removeEventListener("balanceUpdated", fetchTransactions);
  }, [userEmail]);

  const transactions = userData?.history || [];

  // PDF Receipt Generator
  const downloadSingleReceipt = (tx: any) => {
    const doc = new jsPDF({ unit: "mm", format: [100, 150] });
    doc.setFontSize(16);
    doc.setTextColor(30, 80, 255);
    doc.text("NovaPay Receipt", 10, 20);
    doc.setDrawColor(200, 200, 200);
    doc.line(10, 25, 90, 25);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Date: ${new Date(tx.date).toLocaleString()}`, 10, 35);
    doc.text(`Transaction ID: ${tx.transactionId}`, 10, 42);
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text(`Type: ${tx.type.toUpperCase()}`, 10, 55);
    doc.text(`Amount: ${tx.amount} ${tx.currency}`, 10, 65);
    doc.text(`Status: Success`, 10, 75);
    doc.setFontSize(8);
    doc.text("Generated by NovaPay Digital Wallet", 10, 100);
    doc.save(`Receipt_${tx.transactionId}.pdf`);
  };

  // Full Statement Generator
  const downloadFullStatement = () => {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text("NovaPay Account Statement", 14, 20);
    doc.setFontSize(10);
    doc.text(`User: ${userEmail}`, 14, 28);
    const tableRows = transactions.map((tx: any) => [
      new Date(tx.date).toLocaleDateString(),
      tx.transactionId,
      tx.type.toUpperCase(),
      `${tx.amount} ${tx.currency}`,
      "Success"
    ]);
    autoTable(doc, {
      startY: 35,
      head: [["Date", "ID", "Type", "Amount", "Status"]],
      body: tableRows,
      theme: "grid",
      headStyles: { fillColor: [30, 80, 255] }
    });
    doc.save(`NovaPay_Statement.pdf`);
  };

  if (loading) return (
    <div className="flex flex-col items-center justify-center min-h-[60vh] gap-3">
      <Loader2 className="animate-spin text-blue-600" size={40} />
      <p className="text-gray-500 animate-pulse"><T>Loading transactions...</T></p>
    </div>
  );

  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-8 p-4 max-w-6xl mx-auto">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-800 dark:text-white"><T>Account Statement</T></h1>
          <p className="text-gray-500 text-sm"><T>View and download your recent wallet activity</T></p>
        </div>
        
        {transactions.length > 0 && (
          <button 
            onClick={downloadFullStatement}
            className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-5 py-2.5 rounded-xl font-semibold transition-all shadow-lg shadow-blue-500/20 active:scale-95"
          >
            <Download size={18} /> <T>Download Statement</T>
          </button>
        )}
      </div>

      {/* Transaction Table Wrapper */}
      <div className="rounded-2xl bg-white dark:bg-[#0c1a2b] border border-blue-100 dark:border-blue-900 shadow-xl overflow-hidden">
        <div className="p-6 border-b dark:border-blue-900 bg-gray-50/50 dark:bg-blue-900/10 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <FileText className="text-blue-600" size={20} />
            <h3 className="font-bold text-blue-900 dark:text-blue-100"><T>Recent Transactions</T></h3>
          </div>
          <span className="text-xs bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300 px-3 py-1 rounded-full font-bold">
            <T>Total</T>: {transactions.length}
          </span>
        </div>

        <div className="overflow-x-auto">
          {transactions.length > 0 ? (
            <div className="min-w-full divide-y dark:divide-blue-900">
              {transactions.map((tx: any) => {
                const normalizedType = tx.type?.toLowerCase().trim().replace(/\s+/g, '_');

                // International transaction types
                const isIntlSend    = normalizedType === "international_send";
                const isIntlReceive = normalizedType === "international_receive";
                const isTopUp       = normalizedType === "wallet_topup";
                const isIntl        = isIntlSend || isIntlReceive || isTopUp;

                // Donation
                const isDonation = normalizedType === "donation";

                // Regular expense types
                const expenseTypes = ["withdraw", "send_money", "bill_payment", "cash_out", "mobile_recharge", "pay_bill", "subscription"];
                const isExpense = isIntlSend || isTopUp || isDonation || expenseTypes.includes(normalizedType);

                // Icon
                const Icon = isDonation ? Heart : isTopUp ? PlusCircle : isIntl ? Globe : isExpense ? ArrowUpRight : ArrowDownLeft;

                // Icon background color
                const iconClass = isDonation
                  ? "bg-pink-100 text-[#e63b60] dark:bg-pink-900/20"
                  : isIntlReceive
                  ? "bg-blue-100 text-blue-600 dark:bg-blue-900/20"
                  : isIntl
                  ? "bg-purple-100 text-purple-600 dark:bg-purple-900/20"
                  : isExpense
                  ? "bg-rose-100 text-rose-600 dark:bg-rose-900/20"
                  : "bg-emerald-100 text-emerald-600 dark:bg-emerald-900/20";

                // Amount + sub-label
                let amountDisplay = "";
                let amountColor   = "";
                let subLabel      = "";

                if (isDonation) {
                  amountDisplay = `-${tx.amount} BDT`;
                  amountColor   = "text-[#e63b60]";
                  subLabel      = `Donated to ${tx.campaignTitle}`;
                } else if (isIntlSend) {
                  amountDisplay = `-${tx.amountSent} ${tx.fromCurrency}`;
                  amountColor   = "text-rose-500";
                  subLabel      = `→ ${tx.amountReceived} ${tx.toCurrency} • Fee: ${tx.fee} ${tx.fromCurrency}`;
                } else if (isIntlReceive) {
                  amountDisplay = `+${tx.amountReceived} ${tx.toCurrency}`;
                  amountColor   = "text-blue-500";
                  subLabel      = `from ${tx.senderEmail}`;
                } else if (isTopUp) {
                  amountDisplay = `+${tx.amountAdded} ${tx.toCurrency}`;
                  amountColor   = "text-purple-500";
                  subLabel      = `−${tx.amountDeducted} ${tx.fromCurrency} from main balance`;
                } else {
                  amountDisplay = `${isExpense ? "-" : "+"}${tx.amount}`;
                  amountColor   = isExpense ? "text-rose-500" : "text-emerald-500";
                  subLabel      = tx.currency || "BDT";
                }

                return (
                  <div key={tx.transactionId} className="flex items-center justify-between px-6 py-5 hover:bg-gray-50 dark:hover:bg-blue-900/5 transition-colors group">
                    <div className="flex items-center gap-4">
                      <div className={`p-3 rounded-full transition-transform group-hover:scale-110 ${iconClass}`}>
                        <Icon size={20} />
                      </div>
                      <div>
                        <div className="flex items-center gap-2">
                          <p className="font-bold text-gray-800 dark:text-gray-100">
                            {tx.description || tx.type}
                          </p>
                          {isIntl && (
                            <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-purple-100 dark:bg-purple-900/30 text-purple-600 dark:text-purple-300 uppercase tracking-wide">
                              <T>International</T>
                            </span>
                          )}
                          {isDonation && (
                            <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-pink-100 dark:bg-pink-900/30 text-[#e63b60] uppercase tracking-wide">
                              <T>Donation</T>
                            </span>
                          )}
                        </div>
                        <p className="text-xs text-gray-500 mt-1">
                          {new Date(tx.date).toLocaleDateString()} • {new Date(tx.date).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}
                        </p>
                      </div>
                    </div>

                    <div className="flex items-center gap-4 md:gap-10 text-right">
                      <div>
                        <p className={`text-lg font-bold ${amountColor}`}>{amountDisplay}</p>
                        <p className="text-[10px] text-gray-400 mt-0.5">{subLabel}</p>
                      </div>
                      <button
                        onClick={() => downloadSingleReceipt(tx)}
                        className="p-2.5 rounded-lg bg-gray-100 dark:bg-gray-800 text-gray-500 hover:bg-blue-600 hover:text-white transition-all active:scale-90"
                      >
                        <Printer size={18} />
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          ) : (
            <div className="py-20 text-center">
              <FileText size={60} className="mx-auto text-gray-200 dark:text-gray-800 mb-4" />
              <p className="text-gray-500 font-medium"><T>No activity found in your history.</T></p>
            </div>
          )}
        </div>
      </div>
    </motion.div>
  );
}