"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { ArrowUpRight, ArrowDownLeft, Loader2, Download, FileText, Printer } from "lucide-react";
import { useSession } from "next-auth/react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function TransactionsPage() {
  const { data: session } = useSession();
  const [userData, setUserData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  const userEmail = session?.user?.email;

  // ডেটা ফেচ করার ফাংশন
  const fetchTransactions = async () => {
    try {
      setLoading(true);
      const res = await fetch(`/api/kyc?email=${userEmail}`);  
      const data = await res.json();
      setUserData(data);
    } catch (error) {
      console.error("Failed to fetch data", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (userEmail) fetchTransactions();
    
    // ব্যালেন্স আপডেট হলে অটো রিফ্রেশ করার জন্য লিসেনার
    window.addEventListener("balanceUpdated", fetchTransactions);
    return () => window.removeEventListener("balanceUpdated", fetchTransactions);
  }, [userEmail]);

  const transactions = userData?.history || [];

  // ১টি ট্রানজেকশন স্লিপ ডাউনলোড
  const downloadSingleReceipt = (tx: any) => {
    const doc = new jsPDF({
        unit: "mm",
        format: [100, 150] 
    });

    doc.setFontSize(16);
    doc.setTextColor(30, 80, 255);
    doc.text("NovaPay Receipt", 10, 20);
    
    doc.setDrawColor(200, 200, 200);
    doc.line(10, 25, 90, 25);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Date: ${new Date(tx.date).toLocaleString()}`, 10, 35);
    doc.text(`Transaction ID: ${tx.transactionId}`, 10, 42);
    
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text(`Type: ${tx.type.toUpperCase()}`, 10, 55);
    doc.text(`Amount: ${tx.amount} ${tx.currency}`, 10, 65);
    doc.text(`Status: Success`, 10, 75);

    doc.setFontSize(8);
    doc.text("Generated by NovaPay Digital Wallet", 10, 100);

    doc.save(`Receipt_${tx.transactionId}.pdf`);
  };

  // ফুল স্টেটমেন্ট ডাউনলোড
  const downloadFullStatement = () => {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text("NovaPay Account Statement", 14, 20);
    doc.setFontSize(10);
    doc.text(`User: ${userEmail}`, 14, 28);
    
    const tableRows = transactions.map((tx: any) => [
      new Date(tx.date).toLocaleDateString(),
      tx.transactionId,
      tx.type.toUpperCase(),
      `${tx.amount} ${tx.currency}`,
      "Success"
    ]);

    autoTable(doc, {
      startY: 35,
      head: [["Date", "ID", "Type", "Amount", "Status"]],
      body: tableRows,
      theme: "grid",
      headStyles: { fillColor: [30, 80, 255] }
    });

    doc.save(`NovaPay_Statement.pdf`);
  };

  if (loading) return (
    <div className="flex flex-col items-center justify-center min-h-[60vh] gap-3">
      <Loader2 className="animate-spin text-blue-600" size={40} />
      <p className="text-gray-500 animate-pulse">Loading transactions...</p>
    </div>
  );

  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-8 p-4 max-w-6xl mx-auto">
      
      {/* Header Section */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-800 dark:text-white">Account Statement</h1>
          <p className="text-gray-500 text-sm">View and download your recent wallet activity</p>
        </div>
        
        {transactions.length > 0 && (
          <button 
            onClick={downloadFullStatement}
            className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-5 py-2.5 rounded-xl font-semibold transition-all shadow-lg shadow-blue-500/20 active:scale-95"
          >
            <Download size={18} />
            Download Statement
          </button>
        )}
      </div>

      {/* Transactions List */}
      <div className="rounded-2xl bg-white dark:bg-[#0c1a2b] border border-blue-100 dark:border-blue-900 shadow-xl overflow-hidden">
        <div className="p-6 border-b dark:border-blue-900 bg-gray-50/50 dark:bg-blue-900/10 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <FileText className="text-blue-600" size={20} />
            <h3 className="font-bold text-blue-900 dark:text-blue-100">Recent Transactions</h3>
          </div>
          <span className="text-xs bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300 px-3 py-1 rounded-full font-bold">
            Total: {transactions.length}
          </span>
        </div>

        <div className="overflow-x-auto">
          {transactions.length > 0 ? (
            <div className="min-w-full divide-y dark:divide-blue-900">
              {[...transactions].reverse().map((tx: any) => {
                // লজিক: এই টাইপগুলোতে টাকা মাইনাস দেখাবে
                const expenseTypes = ["withdraw", "send_money", "bill_payment", "cash_out", "mobile_recharge", "subscription"];
                const isExpense = expenseTypes.includes(tx.type?.toLowerCase());
                
                return (
                  <div key={tx.transactionId} className="flex items-center justify-between px-6 py-5 hover:bg-gray-50 dark:hover:bg-blue-900/5 transition-colors group">
                    <div className="flex items-center gap-4">
                      <div className={`p-3 rounded-full transition-transform group-hover:scale-110 ${!isExpense ? "bg-emerald-100 text-emerald-600 dark:bg-emerald-900/20" : "bg-rose-100 text-rose-600 dark:bg-rose-900/20"}`}>
                        {!isExpense ? <ArrowDownLeft size={20} /> : <ArrowUpRight size={20} />}
                      </div>
                      <div>
                        <p className="font-bold text-gray-800 dark:text-gray-100 capitalize">
                          {tx.description || tx.type.replace('_', ' ')}
                        </p>
                        <p className="text-xs text-gray-500 mt-1">
                          {new Date(tx.date).toLocaleDateString()} • {new Date(tx.date).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}
                        </p>
                      </div>
                    </div>
                    
                    <div className="flex items-center gap-4 md:gap-10 text-right">
                      <div>
                        <p className={`text-lg font-bold ${!isExpense ? "text-emerald-500" : "text-rose-500"}`}>
                          {!isExpense ? "+" : "-"}{tx.amount} <span className="text-sm font-normal text-gray-400">{tx.currency || "BDT"}</span>
                        </p>
                        <p className="text-[10px] uppercase font-bold text-gray-400 tracking-widest">Completed</p>
                      </div>

                      <button 
                        onClick={() => downloadSingleReceipt(tx)}
                        className="p-2.5 rounded-lg bg-gray-100 dark:bg-gray-800 text-gray-500 hover:bg-blue-600 hover:text-white transition-all active:scale-90"
                      >
                        <Printer size={18} />
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          ) : (
            <div className="py-20 text-center">
              <div className="relative inline-block mb-4">
                <FileText size={60} className="mx-auto text-gray-200 dark:text-gray-800" />
                <div className="absolute inset-0 flex items-center justify-center">
                   <div className="w-2 h-2 bg-blue-500 rounded-full animate-ping"></div>
                </div>
              </div>
              <p className="text-gray-500 font-medium">No activity found in your history.</p>
              <p className="text-gray-400 text-sm">Start by adding money or making a transaction.</p>
            </div>
          )}
        </div>
      </div>
    </motion.div>
  );
}